
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version V-2023.12                           ***
***                      (2.8515123, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2023 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'cdsl29.cdsl.iitbbs.ac.in' by user 'cdsllab'
Binary '/cad/synopsys/sentaurus/V-2023.12/tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 -job 1 -swb_pid 5343 -gsub_pid 527852 -gsub_host cdsl29.cdsl.iitbbs.ac.in -gsub_port 44949 /home/cdsllab/Sarthak_Shantaneel/mosfet_copy'
Current directory '/home/cdsllab/Sarthak_Shantaneel/mosfet_copy'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/cad/synopsys/sentaurus/V-2023.12
	STRELEASE=current
	STROOT_LIB=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib
	STDB=/home/cdsllab
	DATEX=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib/datexcodes.txt
	DISPLAY=:1

Project '/home/cdsllab/Sarthak_Shantaneel/mosfet_copy'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/home/cdsllab/Sarthak_Shantaneel/mosfet_copy/gtree.dat'
Loading jobs and dependence graph '"/home/cdsllab/Sarthak_Shantaneel/mosfet_copy/gexec.cmd"'
Loading project variables '/home/cdsllab/Sarthak_Shantaneel/mosfet_copy/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/MOSFET_dvs.cmd
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/MOSFET_dvs.cmd for node 1
+++Preprocessing results written to /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/pp1_dvs.cmd
Start Simulation section
16:45:45 Sep 07 2026     job 1 <sde> started on host 'cdsl29.cdsl.iitbbs.ac.in': "sde -l n1_dvs.cmd"
16:46:01 Sep 07 2026 +++ job 1 <sde> done: exit(0)
End Simulation section
Start Epilogue section
16:46:01 Sep 07 2026 *** job 1 pre/post execution: eval " gjob::find_extracted_vars "/home/cdsllab/Sarthak_Shantaneel/mosfet_copy" n1_dvs.out 1 "
End Epilogue section
Job succeeded
gjob exits with status 0
