
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version V-2023.12                           ***
***                      (2.8515123, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2023 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'cdsl29.cdsl.iitbbs.ac.in' by user 'cdsllab'
Binary '/cad/synopsys/sentaurus/V-2023.12/tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 --max_threads 4 -job 2 -swb_pid 1030421 -gsub_pid 1056422 -gsub_host cdsl29.cdsl.iitbbs.ac.in -gsub_port 33101 /home/cdsllab/Sarthak_Shantaneel/mosfet_copy'
Current directory '/home/cdsllab/Sarthak_Shantaneel/mosfet_copy'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/cad/synopsys/sentaurus/V-2023.12
	STRELEASE=current
	STROOT_LIB=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib
	STDB=/home/cdsllab
	DATEX=/cad/synopsys/sentaurus/V-2023.12/tcad/current/lib/datexcodes.txt
	DISPLAY=localhost:10.0

Project '/home/cdsllab/Sarthak_Shantaneel/mosfet_copy'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/home/cdsllab/Sarthak_Shantaneel/mosfet_copy/gtree.dat'
Loading jobs and dependence graph '"/home/cdsllab/Sarthak_Shantaneel/mosfet_copy/gexec.cmd"'
Loading project variables '/home/cdsllab/Sarthak_Shantaneel/mosfet_copy/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/sdevice_des.cmd
Reading file /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/sdevice.par
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/sdevice_des.cmd for node 2
'@tdr@' creates dependences with the node(s) '1'
+++Preprocessing results written to /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/pp2_des.cmd
The node '2' has dependencies to the node(s) '1'
---------------------------------------
Preprocessing file /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/sdevice.par for node 2
+++Preprocessing results written to /home/cdsllab/Sarthak_Shantaneel/mosfet_copy/pp2_des.par
The node '2' has dependencies to the node(s) '1'
Start Simulation section
06:33:53 Sep 06 2026     job 2 <sdevice> started on host 'cdsl29.cdsl.iitbbs.ac.in': "sdevice --max_threads 4  pp2_des.cmd"
06:33:56 Sep 06 2026 +++ job 2 <sdevice> done: exit(0)
End Simulation section
Start Epilogue section
06:33:56 Sep 06 2026 *** job 2 pre/post execution: eval " gjob::find_extracted_vars "/home/cdsllab/Sarthak_Shantaneel/mosfet_copy" n2_des.out 2 "
End Epilogue section
Job succeeded
gjob exits with status 0
